### ISSUE TITLE
generate mnemonic from seed?

### ISSUE THREAD

**Issue by misuqian** [BitcoinCashKit/BitcoinKit#56]

**Comment by usatie** [comment]
Hi thanks for the creating a issue for asking a question.

This is the flow of data.
`entropy <-> mnemonic words -> seed -> privkey -> pubkey -> addr`

So, `entropy -> mnemonic words` and `mnemonic words -> entropy` are both possible, but `seed -> mnemonic words` is impossible.

Thanks!
