### ISSUE TITLE
Can i use 'BitcoinKit' Framework Implement 'Send btc' function in testnet?

### ISSUE THREAD

**Issue by victorylau** [BitcoinCashKit/BitcoinKit#66]
I saw no code in SendViewController.swift.
Thanks!

**Comment by usatie** [comment]
Hi, thanks for asking this question!
We implemented send feature in SendViewController.swift in our PR.
So after merging this PR, you can see codes there!

**Comment by victorylau** [comment]
@usatie thanks a lot ,i debug your code, i saw it is a BCH wallet?is not BTC wallet?

**Comment by victorylau** [comment]
@usatie i found the Class Network, i change value testnetBTC ...Thanks a lot again!

**Comment by usatie** [comment]
@victorylau It's my pleasure to be your help!
Thanks for giving us a comment.

If you have other questions or another request, feel free to create an issue again!
