### ISSUE TITLE
💫Announcement💫 Rename the organization/repository

### ISSUE THREAD

**Issue by usatie** [BitcoinCashKit/BitcoinKit#72]
We're thinking of renaming both/part of organization name and repository name.
This is what we are thinking of. Please give us a feedback!
We want to decide and fix the organization name and repository name as soon as possible.

**It'll be decided at least until 8/15.**

There are several possibilities of renaming .
Priority order is bellow.
## 1. BitcoinKit/BitcoinKit
We think it'd be the best.
The problem is, the organization name BitcoinKit is already taken.
The organization seems to be not so much active for about 3 years, so we are negotiating the owner if they give it to us or not.

## 2. yenom/BitcoinKit
We think this would be the second best.
Since the maintainer for now is almost equal to Yenom developers, it can be the best option.

Dominating or controlling the project is not our aim, instead we want to see broad collaboration.
I think transferring the ownership to a company is not good idea from this perspective.

## 3. BitcoinCashKit/BitcoinCashKit
We think this would be the third best.

We're planning to keep compatibility of both BCH/BTC for as long as possible.
We'll choose BCH when we have to choose one of them. 
e.g. The situation that keeping compatibility is too difficult.
Renaming the repository name to be `BitcoinCashKit` is good because the name makes it clear.

However, we'll try our best to keep compatibility. 
And we believe `BitcoinKit` is far better from the branding perspective.

## Other options
4. yenom/BitcoinCashKit
Right now this is Yenom developers' working repo.

5. BitcoinCashKit/BitcoinKit
This is current situation.

**Comment by kzumu** [comment]
I agree with 1st, and 2nd.
The reason is same to above.
2nd option is as better as 1st.
It is yenom has BitcoinCashKit repository, so two repository of library will be grouped.

**Comment by usatie** [comment]
## 2. yenom/BitcoinKit
We decided to choose this one.
We tried to get the organization name `BitcoinKit`, we're not able to get it.
So this repository will be `yenom/BitcoinKit.
Thanks.
